site_name: MDE Internals
site_url: https://therustymate.com/MDE-Internals
repo_url: https://github.com/therustymate/MDE-Internals
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: General Sans
extra:
  homepage: https://therustymate.com/MDE-Internals
plugins:
  - search